-- MySQL Script generated by MySQL Workbench
-- Sat Nov  4 10:11:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema qatar2022
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema qatar2022
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `qatar2022` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `qatar2022` ;

-- -----------------------------------------------------
-- Table `qatar2022`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qatar2022`.`Departamento` (
  `idDepartamento` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `presupuesto` DOUBLE NULL,
  PRIMARY KEY (`idDepartamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `qatar2022`.`Empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `qatar2022`.`Empleado` (
  `idEmpleado` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `nacionalidad` VARCHAR(45) NULL,
  `dni` INT NULL,
  `Departamento` INT NOT NULL,
  INDEX `Departamento_idx` (`Departamento` ASC) VISIBLE,
  PRIMARY KEY (`idEmpleado`),
  CONSTRAINT `Departamento`
    FOREIGN KEY (`Departamento`)
    REFERENCES `qatar2022`.`Departamento` (`idDepartamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
